/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.dao.PersonDao;
import com.example.models.Person;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {

    public static void main(String[] args) {

        ApplicationContext appContext = new ClassPathXmlApplicationContext("beans.xml");

        PersonDao pd = appContext.getBean("PersonDao", PersonDao.class);

        Person ethan = new Person(0, "Ethan", "McGill", "elmcgill", "password");

        pd.insert(ethan);

        System.out.println(pd.selectPersonById(1));

        System.out.println(pd.getUserByUsernameAndPassword("elmcgill", "pass"));

    }
}
