/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.dao.*;
import com.example.models.GroceryItem;
import com.example.models.GroceryList;
import com.example.models.Person;
import com.example.services.GroceryItemService;
import com.example.services.GroceryListService;
import com.example.services.PersonService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.util.ArrayList;

public class App {

    private static IPersonDao pDao;
    private static PersonService pServ;

    private static IGroceryDao gDao;
    private static GroceryItemService gServ;


    /*
    private static IGroceryListDao glDao = new GroceryListDao();
    private static GroceryListService glService = new GroceryListService(glDao)
     */
    private static IGroceryListDao glDao;

    private static GroceryListService glServ;

    //Previously
    /*
        private static IPersonDao pDao = new PersonDaoMock();
        private static PersonService pServ = new PersonService(pDao);
     */

    public static void main(String[] args) {

        ApplicationContext appContext = new ClassPathXmlApplicationContext("beans.xml");

        pDao = appContext.getBean("PersonDaoBean", PersonDaoMock.class);
        pServ = appContext.getBean("PersonServiceBean", PersonService.class);

        gDao = appContext.getBean("GroceryItemDao", GroceryDaoMock.class);
        gServ = appContext.getBean("GroceryItemService", GroceryItemService.class);

        glDao = appContext.getBean("GroceryListDao", GroceryListDao.class);
        glServ = appContext.getBean("GroceryListService", GroceryListService.class);

        Person ethan = pServ.register("Ethan", "McGill", "elmcgill", "password");

        System.out.println(pDao.getPerson(ethan));

        GroceryItem gi = gServ.addItem("Milk", 2.00);

        System.out.println(gDao.getItem(gi));

        ArrayList<GroceryItem> gList = new ArrayList<>();
        gList.add(gi);

        GroceryList gl = glServ.createGroceryList(ethan, gList);

        System.out.println(glDao.getGroceryList(gl));

    }
}
