/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.sql.*;

public class App {

    //We will need to create a connection to the database to use
    //We will use the DriverManager to get said connection

    public static Connection con = null;

    //We need the db url, user, and password to make our connection
    public static final String URL = "jdbc:postgresql://localhost:5432/socialdb";
    public static final String USERNAME = "dbuser";
    public static final String PASSWORD = "password";

    public static void main(String[] args) {

        try{

            con = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            System.out.println("Connection successful");

        } catch(SQLException e){
            e.printStackTrace();
        }

        insert(7, "Ethan McGill", "ethan.mcgill@mail.com", "emcgill", "password", new Date(1587422499000l), "This is my first post", 0);

        selectAll();


    }

    public static void insert(int id, String name, String email, String username, String password, Date joined, String postContent, int followerid){
        String sql = "insert into social values" +
                "(" + id +",'" + name + "','" + email + "','" + username + "','" + password + "','" + joined + "','" + postContent + "'," + followerid + ")";

        System.out.println(sql);

        try{
            Statement s = con.createStatement();
            s.execute(sql);
        } catch(SQLException e){
            e.printStackTrace();
        }

    }

    public static void selectAll(){
        String sql = "select * from social";

        try{

            //This will create our statement object
            Statement s = con.createStatement();

            //We execute the statement from above, with the SQL statement we want to execute
            ResultSet rs = s.executeQuery(sql);

            String result = "";

            //ResultSet .next method will return true, until there are no more entries in the result set
            while(rs.next()){
                result = "";
                result += "social: {\n";
                result += "\tid: " + rs.getInt(1) + ",\n";
                result += "\tname: " + rs.getString(2) + ",\n";
                result += "\temail: " + rs.getString(3) + ",\n";
                result += "\tusername: " + rs.getString(4) + ",\n";
                result += "\tpassword: " + rs.getString(5) + ",\n";
                result += "\tjoined: " + rs.getDate(6).toString() + ",\n";
                result += "\tpostcontent: " + rs.getString(7) + ",\n";
                result += "\tfollowerid: " + rs.getInt(8) + ",\n}";
                System.out.println(result);
            }

        } catch(SQLException e){
            e.printStackTrace();
        }
    }


}
