/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.models.*;
import com.revature.services.*;
import com.revature.dao.*;
import com.revature.exceptions.UsernameOrPasswordIncorrectException;
import java.util.Scanner;
import java.util.List;
import java.util.Iterator;
import java.util.Set;

public class Driver {

    private static IUserDao uDao = new UserDaoMock();
    private static UserService uServ = new UserService(uDao);
    private static IPostDao pDao = new PostDaoMock();
    private static PostService pServ = new PostService(pDao);

    public static void main(String[] args) {

        Scanner scan = new Scanner(System.in);
        boolean isDone = false;
        User loggedIn = null;

        MockUserDB.getInstance().populateUsers();
        MockPostDB.getInstance().populatePosts();

        //While the user is not done, continue running the application
        System.out.println("Hello, welcome to the worst social media app");
        while(!isDone){
            
            //We can use a if statement to see if the loggedIn user is null, if they are
            //Then they need to login or register an account

            if(loggedIn == null){
                //Do the login/register logic here
                System.out.println("Seems like you aren't logged in partner");
                System.out.println("Would you like to login or register?");
                System.out.println("Choose 1 to register, choose 2 to login");
                String input = scan.nextLine();
                if(input.equals("1")){
                    //Do the register logic
                    System.out.println("What is your first name?");
                    String first = scan.nextLine();
                    System.out.println("What is your last name?");
                    String last = scan.nextLine();
                    System.out.println("What do you want your username to be?");
                    String username = scan.nextLine();
                    System.out.println("What is your email?");
                    String email = scan.nextLine();
                    System.out.println("What is your password?");
                    String password = scan.nextLine();
                    uServ.registerUser(first, last, username, email, password);
                }
                else {
                    System.out.println("What is your username:");
                    String username = scan.nextLine();
                    System.out.println("What is your password?");
                    String password = scan.nextLine();
                    try{
                        loggedIn = uServ.loginUser(username, password);
                        System.out.println(loggedIn);
                    } catch(UsernameOrPasswordIncorrectException e){
                        e.printStackTrace();
                    }
                    
                }
            } else {
                System.out.println("Looks like you got logged in");
                System.out.println("What would you like to do next?");
                System.out.println("Choose 1 to create a post, 2 to view your feed");
                System.out.println("3 to search for new people to follow");
                int input = scan.nextInt();
                scan.nextLine();
                switch(input){
                    case 1:
                        System.out.println("Please enter your content");
                        String content = scan.nextLine();
                        pServ.createPost(loggedIn, content);
                        break;
                    case 2:
                        Set<Post> feed = pServ.getUserFeed(loggedIn);

                        Iterator<Post> pIterator = feed.iterator();

                        while(pIterator.hasNext()){
                            Post p = pIterator.next();
                            System.out.println(p.getUser().getUsername() + "\t\t\t\t" + p.getTimeStamp().toString());
                            System.out.println(p.getContent());
                            System.out.println();
                        }
                        break;
                    case 3:
                        //Showing an iterator
                        List<User> uList = uServ.getTopUsers();
                        Iterator<User> uIter = uList.iterator();
                        System.out.println("Username\t\t\t\t\tFollowers");
                        while(uIter.hasNext()){
                            User u = uIter.next();
                            System.out.println(u.getUsername() +"\t\t\t\t\t" + u.getFollowers().size());
                        }
                        System.out.println("Who would you like to follow?");
                        System.out.println("Enter their username below:");
                        String username = scan.nextLine();
                        uServ.followUser(loggedIn, username);
                        break;
                }

                System.out.println("Are you finished? Y/N");
                String response = scan.nextLine();
                //Use a fancy ternary operated I mentioned but never used
                isDone = response.equals("Y") ? true : false;

            }

        }
    }
}
