/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.controllers.PostController;
import com.example.controllers.UserController;
import com.example.dao.IPostDao;
import com.example.dao.IUserDao;
import com.example.dao.PostDaoJDBC;
import com.example.dao.UserDaoJDBC;
import com.example.services.PostService;
import com.example.services.UserService;
import com.example.utils.ConnectionSingleton;
import io.javalin.Javalin;
import io.javalin.http.staticfiles.Location;

import java.sql.Connection;

import static io.javalin.apibuilder.ApiBuilder.*;

public class SocialApiDriver {

    public static void main(String[] args) {

        IUserDao ud = new UserDaoJDBC();



        IPostDao pd = new PostDaoJDBC();
        PostService ps = new PostService(pd);
        UserService us = new UserService(ud, pd);
        UserController uc = new UserController(us);
        PostController pc = new PostController(ps);

        Javalin server = Javalin.create(config -> {
            config.addStaticFiles("/public", Location.CLASSPATH);
            config.enableCorsForAllOrigins();
        });

        server.before(ctx -> ctx.header("Access-Control-Allow-Credentials", "true"));
        server.before(ctx -> ctx.header("Access-Control-Expose-Headers", "*"));
        server.routes(()-> {
            path("users", () -> {
                post("/register", uc.handleRegister);
                post("/login", uc.handleLogin);
                put("/", uc.handleUpdateUser);
                delete("/{id}", uc.handleDeleteUser);
                get("/follow/{id}", uc.handleFollowUser);
                get("/full/{id}", uc.handleFullUserObject);
                get("/logout", uc.handleLogout);
            });
            path("posts", () -> {
                post("/", pc.handleCreatePost);
                get("/", pc.handleGetUserPosts);
            });
        });

        server.start(8000);

    }
}
