/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.controllers.UserController;
import com.example.dao.IUserDao;
import com.example.dao.UserDaoJDBC;
import com.example.services.UserService;
import com.example.utils.ConnectionSingleton;
import io.javalin.Javalin;

import java.sql.Connection;

import static io.javalin.apibuilder.ApiBuilder.path;
import static io.javalin.apibuilder.ApiBuilder.post;

public class SocialApiDriver {

    public static void main(String[] args) {

        IUserDao ud = new UserDaoJDBC();
        UserService us = new UserService(ud);
        UserController uc = new UserController(us);

        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.routes(()-> {
            path("users", () -> {
                post("/register", uc.handleRegister);
            });
        });

        server.start(8000);

    }
}
