/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.service.SomeOtherService;
import com.example.service.UserService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {

    public static void main(String[] args) {
        ApplicationContext appContext = new ClassPathXmlApplicationContext("beans.xml");

        UserService uServ = appContext.getBean("UserServiceBean", UserService.class);
        SomeOtherService soServ = appContext.getBean("SomeOtherService", SomeOtherService.class);

        System.out.println(uServ.createUser("ethan", "password"));

        try {
            uServ.login("Ethan", "Password");
        } catch (Exception e) {
        }

        try{
            uServ.login("ethan", "password");
        } catch(Exception e){

        }

        System.out.println(uServ.updateUser(uServ.createUser("Ethan", "password")));

        soServ.printHello();

    }
}
